# --
# --
# This software comes with ABSOLUTELY NO WARRANTY. For details, see
# the enclosed file COPYING for license information (GPL). If you
# did not receive this file, see https://www.gnu.org/licenses/gpl-3.0.txt.
# --

#
# WARNING: This file is autogenerated from "scripts/auto_build/spec/templates" via
# "bin/buzzdesk.Console.pl Dev::Tools::RPMSpecGenerate". All changes will be lost.
#

Summary:      The BuzzDesk service desk.
Name:         buzzdesk
Version:      0.0
License:      GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
Group:        Applications/Mail
Provides:     buzzdesk
Obsoletes:    otrs <= 6.0.30
Requires:     bash-completion cronie httpd mod_perl perl perl(Archive::Zip) perl(Crypt::Eksblowfish::Bcrypt) perl(Date::Format) perl(DateTime) perl(DBI) perl(Encode::HanExtra) perl(IO::Socket::SSL) perl(JSON::XS) perl(LWP::UserAgent) perl(Mail::IMAPClient) perl(Net::DNS) perl(Net::LDAP) perl(Template) perl(Text::CSV) perl(Text::CSV_XS) perl(URI) perl(XML::LibXML) perl(XML::LibXSLT) perl(XML::Parser) perl(YAML::XS) perl-core procmail
AutoReqProv:  no
Release:      01
Source0:      buzzdesk-%{version}.tar.bz2
BuildArch:    noarch
BuildRoot:    %{_tmppath}/%{name}-%{version}-build

%description
BuzzDesk is an Open source Ticket Request System with many features to manage
customer telephone calls and e-mails. It is distributed under the GNU
General Public License (GPL) and tested on Linux and Mac OS. Do you
receive many e-mails and want to answer them with a team of agents?
You're going to love BuzzDesk!

%prep
%setup

%build
# copy config file
cp Kernel/Config.pm.dist Kernel/Config.pm
# rename config POD file
mv Kernel/Config.pod.dist Kernel/Config.pod
# copy all crontab dist files
for foo in var/cron/*.dist; do mv $foo var/cron/`basename $foo .dist`; done
# copy all .dist files
cp .procmailrc.dist .procmailrc
cp .fetchmailrc.dist .fetchmailrc
cp .mailfilter.dist .mailfilter

%install
# delete old RPM_BUILD_ROOT
rm -rf $RPM_BUILD_ROOT
# set DESTROOT
export DESTROOT="/opt/buzzdesk/"
# create RPM_BUILD_ROOT DESTROOT
mkdir -p $RPM_BUILD_ROOT/$DESTROOT/
# copy files
cp -R . $RPM_BUILD_ROOT/$DESTROOT
# configure apache
install -d -m 755 $RPM_BUILD_ROOT/etc/httpd/conf.d
install -m 644 scripts/apache2-httpd.include.conf $RPM_BUILD_ROOT/etc/httpd/conf.d/zzz_buzzdesk.conf

# set permission

export BUZZDESKUSER=buzzdesk
useradd $BUZZDESKUSER || :
useradd apache || :
groupadd apache || :
$RPM_BUILD_ROOT/opt/buzzdesk/bin/buzzdesk.SetPermissions.pl --web-group=apache

%pre
# useradd
export BUZZDESKUSER=buzzdesk
echo -n "Check BuzzDesk user ... "
if id $BUZZDESKUSER >/dev/null 2>&1; then
    echo "$BUZZDESKUSER exists."
    # update groups
    usermod -g apache $BUZZDESKUSER
    # update home dir
    usermod -d /opt/buzzdesk $BUZZDESKUSER
else
    useradd $BUZZDESKUSER -d /opt/buzzdesk/ -s /bin/bash -g apache -c 'BuzzDesk System User' && echo "$BUZZDESKUSER added."
fi


%post
export BUZZDESKUSER=buzzdesk

# note
HOST=`hostname -f`
echo ""
echo "Next steps: "
echo ""
echo "[restart web server]"
echo " systemctl restart apache2.service"
echo ""
echo "[install the BuzzDesk database]"
echo " Make sure your database server is running."
echo " Use a web browser and open this link:"
echo " http://$HOST/buzzdesk/installer.pl"
echo ""
echo "[start BuzzDesk daemon and corresponding watchdog cronjob]"
echo " /opt/buzzdesk/bin/buzzdesk.Daemon.pl start"
echo " /opt/buzzdesk/bin/Cron.sh start"
echo ""

%clean
rm -rf $RPM_BUILD_ROOT

%files
%config /etc/httpd/conf.d/zzz_buzzdesk.conf

%defattr(-, buzzdesk, apache, -)
%config(noreplace) /opt/buzzdesk/Kernel/Config.pm
%attr(-, buzzdesk, root,) %config(noreplace) /opt/buzzdesk/.procmailrc
%config(noreplace) /opt/buzzdesk/.fetchmailrc
%config(noreplace) /opt/buzzdesk/.mailfilter

%dir /opt/buzzdesk
/opt/buzzdesk/RELEASE
/opt/buzzdesk/ARCHIVE
/opt/buzzdesk/.bash_completion
/opt/buzzdesk/.procmailrc.dist
/opt/buzzdesk/.fetchmailrc.dist
/opt/buzzdesk/.mailfilter.dist

%dir /opt/buzzdesk/Custom/
/opt/buzzdesk/Custom/README

%dir /opt/buzzdesk/Kernel/

%dir /opt/buzzdesk/Kernel/Config/
/opt/buzzdesk/Kernel/Config.pm.dist
/opt/buzzdesk/Kernel/Config.pod
/opt/buzzdesk/Kernel/Config/Files/
/opt/buzzdesk/Kernel/Config/Defaults.pm

/opt/buzzdesk/Kernel/GenericInterface*

/opt/buzzdesk/Kernel/Language.pm
%dir /opt/buzzdesk/Kernel/Language/
/opt/buzzdesk/Kernel/Language/*.pm

/opt/buzzdesk/bin*
/opt/buzzdesk/Kernel/Autoload*
/opt/buzzdesk/Kernel/Modules*
/opt/buzzdesk/Kernel/Output*
/opt/buzzdesk/Kernel/System*
/opt/buzzdesk/scripts*
/opt/buzzdesk/i18n/BuzzDesk/*

%dir /opt/buzzdesk/var/
%dir /opt/buzzdesk/var/article/
/opt/buzzdesk/var/fonts/
/opt/buzzdesk/var/httpd/
%dir /opt/buzzdesk/var/cron/
%dir /opt/buzzdesk/var/log/
%dir /opt/buzzdesk/var/sessions/
%dir /opt/buzzdesk/var/spool/
/opt/buzzdesk/var/cron/*
%dir /opt/buzzdesk/var/tmp/
%dir /opt/buzzdesk/var/stats/
/opt/buzzdesk/var/stats/*.xml
%dir /opt/buzzdesk/var/stats/formatdefinition/excel/
/opt/buzzdesk/var/stats/formatdefinition/excel/*
%dir /opt/buzzdesk/var/processes/examples/
/opt/buzzdesk/var/processes/examples/*
%dir /opt/buzzdesk/var/webservices/examples/
/opt/buzzdesk/var/webservices/examples/*.pm
/opt/buzzdesk/var/webservices/examples/*.yml

/opt/buzzdesk/Kernel/cpan-lib*

%doc /opt/buzzdesk/*.md
%doc /opt/buzzdesk/COPYING
%doc /opt/buzzdesk/COPYING-Third-Party
%doc /opt/buzzdesk/doc*
